msgFilterMode:
  groupFilterMode: 2 #0不过滤，1采用黑名单方式，2采用白名单方式，对应的表是 PermissionList
  privateFilterMode: 2 # 同上
botName:
  name: Isara # 一般用于自我称呼
  fullName: 19岁现役JD Isara # 全称，一般是在转发消息这种地方使用
  lowerCasedName: isara # 用于一些指令匹配的地方，最好小写
  id: 2096820879 # bot 控制的 QQ id
dataSource:
  port: 27017 # mongoDB 的端口
  auth: false # 是否启用身份验证
  username: null
  password: null
  databaseName: Lealra # 使用的数据库名称
  maxPoolSize: 10
  timeout: 100 #单位：秒
server:
  port: 8081 # 该服务开启的端口
  hostname: 127.0.0.1 # 可以改成 ip 或者域名，nsfw 图的二维码是基于这个生成的
function:
  repeat: true # 是否有概率复读
  makeChoice: true # 对A不A格式的文本是否有反应
  privateDiary: false # 是否开启私人笔记，即无法通过生成二维码直接访问，对应的是 admin 账号
logs:
  msgLogsRefreshCycle: 48 #單位：小時，每小時自動清理
  errLogsRefreshCycle: 3 #單位：天，且新一天到來時就會刪除之前的日志
auth:
  admin:
    - 1730483316 # 管理员账号
aiPaint:
  api: http://91.216.169.75:5010 # 这个功能一开始嫖的别人的，但是好像最近那边的图片获取不太稳定，会考虑把这个功能修复一下
  token:
    - Njm2KthPDsS4nY1lLpOIF7EwzdoBaiGX
    - gjeAFROY9c3N4tWK6GCbnLsyMIoH8q0U
bangumi:
  bangumiSearch: true # 是否开启相关功能
  maxPoolSize: 3 # 同一时间的最大搜索数，所有组群共用
setu:
  picMode: 11 # 图片发送的形式，1为转换为二维码访问，2为原图访问,默认直接发送，十位对应非 nsfw 图，个位对应 nsfw 图
  setuGroupSender: true # 是否能群发，现在改了显示方式已经没有多少被封杀的可能了
  api: https://api.lolicon.app/setu/v2 # https://lolisuki.cc/api/setu/v1
openAi:
  token: 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 #your token
  settings: # 详细配置见官方 api 文档
    chat:
      memory: false # 是否开启记忆化，不建议，token 烧太快
      model: text-davinci-003
      maxTokens: 1024
      temperature: 0.9
      topP: 1
      frequencyPenalty: 0
      presencePenalty: 0.6
    edit:
      model: code-davinci-edit-001
learnAndResponse:
#  只有在你空间属实不够的情况下，考虑白嫖qq图床，否则仍然建议base64，因为qq图床的定期清理很讨厌，虽然做了相应的续期措施，但该措施可能导致其它隐患
  renewSwitch: false
  groupToRenew: 608203511 # 用于续期的群，最好私人群，太吵了
  msgInterval: 2 # 消息间隔，单位s,过短容易出事
  useBase64: true # 空间够用的话强烈建议打开
bilibili:
  status: true # 是否开启，true 开启 false 关闭
  interval: 1 # 单位 s，扫描爬取每个 up 的时间间隔，会上下浮动 0.5 秒
antiCf: # 针对相关反爬的设定
  ja3: "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0"
  userAgent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
  timeout: 200 # 单位s，设置太小了容易收不到回复，看个人情况调整
  proxy: "http://127.0.0.1:7890" # 代理地址，characterAi要翻墙所以必须挂
proxy:
  httpsProxy:
    - http://201.222.45.2:999
    - http://49.0.253.51:8080
    - http://201.222.44.106:999
